config/routes.rb
Blog::Application.routes.draw do

  #match "*path", to: redirect("http://www.google.co.uk")
  resources :posts do 
     resources :comments 
  end
  root :to => "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  commenter  :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

app/models/post.rb
class Post < ActiveRecord::Base

    validates :name, :presence => true #name must be present
    validates :body, :presence => true #name must be present
    validates :title, :presence => true, #title must be present
              :length => {:minimum => 5} #title must have minimum length of 5
    has_many :comments, :dependent => :destroy #delete all comments dependent on a post when a post is deleted 
    has_many :tags
    # has_and_belongs_to_many :posts
    
    accepts_nested_attributes_for :tags, :allow_destroy => true,
                                  :reject_if => proc {|attrs| attrs.all? { |k, v| v.blank? } }
    
    # The :allow_destroy option on the nested attribute declaration tells
    # Rails to display a “remove” checkbox on the view that you’ll build 
    # shortly. The :reject_if option prevents saving new tags that do not
    # have any attributes filled in.
end

# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime

#

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

# == Schema Information
#
# Table name: tags
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id]) #fetch all comments for that post
        @comment = @post.comments.create(params[:comment]) #create link and save the comment
        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("id DESC").page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      gflash :success => "Post has been created!"
      redirect_to @post
    else
      gflash :error => "Post has not been created"
      gflash :notice => "Complete all fields"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes params[:post]
        gflash :notice => "Post updated!"
        redirect_to @post
    else
      gflash :warning => "Message Not Saved!"
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    gflash :success => "Deleted"
    redirect_to :posts
  end
end

app/helpers/application_helper.rb
require 'builder'
module ApplicationHelper
    def textilize(text)
                CodeFormatter.new(text).to_html.html_safe unless text.blank?
            end
            
    def codeeray(text)
        CodeFormatter.new(text).to_html.html_safe unless text.blank?
    end        
            
    def coderay(text)
        text.gsub!(/\<code(?: lang="(.+?)")?\>(.+?)\<\/code\>/m) do 
          code = CodeRay.scan($2, $1).div(:css => :class) 
          "<notextile>#{code}</notextile>" 
        end 
        return text.html_safe
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comment.html.erb
<hr/>
<% unless @post.comments.empty? %>
		<h2>Comments</h2>
		<p>
			<b>Comment by:</b>
			<%= comment.commenter %>
		</p>

		<p>
			<b>Comment:</b>
			<%= coderay comment.body %>
		</p>
		<%#= link_to 'Destroy Comment', [comment.post, comment],
		               :confirm => 'Are you sure?',
		               :method => :delete %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build] do |form| %>
	Name: <%= form.text_field :commenter%><br/>
	Comment:<br/>
	<%= form.text_area :body, :rows => 10 %><br/>
	<%=form.submit "Send Comment" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application" %>
  <%= auto_discovery_link_tag(:rss, "http://damainboss.com") %>
  <%= csrf_meta_tags %>
</head>
<body>
<section class="container_16">
<%= yield %>
</section>

</body>
</html>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for @post do |form| %>
<table>
	<tr>
		<th>Name: </th>
		<td> <%= form.text_field :name %> </td>
	</tr>
	<tr>
		<th>Title: </th>
		<td> <%= form.text_field :title %> </td>
	</tr>
	<tr>
		<th>Content: </th>
		<td> <%= form.text_area :body %> </td>
	</tr>
</table>
	<h2>Tags:</h2>
	<%= render :partial => 'tags/form', :locals => {:form => form }  %>
<%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<article class="post round">
<h2><%= post.title %></h2>
<sub>Posted at <%= post.created_at %>, Last updated at <%= post.updated_at %></sub>
<p>
	<%= coderay post.body %>
</p>

<ul>
  <li><%= pluralize post.comments.count, "comment" %></li>
  <li><%= primary_button_link_to "show", post %></li>
</ul>
</article>

app/views/posts/delete.html.erb
<h1>Post#delete</h1>
<p>Find me in app/views/post/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= gflash %>
<%= render "form" %>

<%= link_to "<< back to show", post_path(@post) %>

app/views/posts/index.html.erb
<h1>Welcome to my sandbox!</h1>
<h1>Please note that this is not a blog! Its just my rails sandbox. I use it to test out stuff ;) </h1>
<%= gflash %>
	
<%= paginate @posts %>  <%= link_to "RSS Feed", posts_url(:rss) %>
	
<%= render @posts %>

<%#= link_to "New Post", new_post_path %> <br>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= gflash %>
<%= render "form" %>

<p><%= link_to "back to posts", "/posts" %></p>

app/views/posts/show.html.erb
<%= gflash %>

<p><%= link_to "<< back to posts", posts_path %></p>

<h1><%= @post.title %></h1>

<article class="post round">
	<%= coderay(@post.body) %></div>
</article>

<ul>
  <li><%#= link_to "edit", edit_post_path(@post) %></li>
  <li><%#= button_link_to "destroy", @post, :method => :delete, :confirm => "Are you sure?" %></li>
</ul>

<!-- <h2>Tags: </h2> -->
<%#= @post.tags.map {|t| t.name}.join(", ") %>
<br/>
<%= render @post.comments %>

 	<h3>Add a comment</h3>
	<%= render "comments/form" %>
<p><%= link_to "<< back to posts", posts_path %></p>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
	<%= tag_form.label :name, 'Tag:'%>
	<%= tag_form.text_field :name %>
	
	<% unless tag_form.object.nil? || tag_form.object.new_record? %>
		<%= tag_form.label :_destroy, 'Remove:'%>
		<%= tag_form.check_box :_destroy%>
	<%end%>
<% end %>
<br/>